name: Build and Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      run: rustup default stable

    - name: Setup rust cache
      uses: Swatinem/rust-cache@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential llvm clang libclang-dev cmake libssl-dev pkg-config python3 git

    - name: Build
      run: |
        cargo install --git https://github.com/immunant/c2rust.git c2rust --locked --root ~/.cargo/bin
    
    - name: Revision
      id: revision
      run: |
        revision=$(curl -s https://api.github.com/repos/immunant/c2rust/commits/master | jq -r .sha)
        echo "revision=$revision" >> $GITHUB_OUTPUT
    
    - name: Update README
      run: |
        readme=$(cat README.md | sed -n 's/Last build: \(.*\)/Last build: ${{ steps.revision.outputs.revision }}/p')
        echo "$readme" > README.md

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Last build: ${{ steps.revision.outputs.revision }}"
        git push
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Nightly build ${{ steps.revision.outputs.revision }}
        body_path: "Last build: ${{ steps.revision.outputs.revision }}"
        fail_on_unmatched_files: true
        files: ~/.cargo/bin/c2rust
