name: Build and Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          artifact_name: c2rust
          asset_postfix: linux-amd64
        # - os: windows-latest
        #   artifact_name: c2rust.exe
        #   asset_postfix: windows-amd64.exe
        - os: macos-latest
          artifact_name: c2rust
          asset_postfix: darwin-amd64
    runs-on: ${{ matrix.os }}
    outputs:
      revision: ${{ steps.revision.outputs.revision }}
      tag: ${{ steps.revision.outputs.tag }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      run: rustup default stable

    - name: Setup rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: ""

    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential llvm clang libclang-14-dev cmake libssl-dev pkg-config python3 git
        echo "LLVM_CONFIG_PATH=/usr/bin/llvm-config-14" >> $GITHUB_ENV
    
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install llvm python3 cmake openssl
        echo "LLVM_CONFIG_PATH=/opt/homebrew/opt/llvm/bin/llvm-config" >> $GITHUB_ENV

    - name: Build
      run: |
        cargo install --git https://github.com/immunant/c2rust.git c2rust --locked --root ~/.cargo/
        cp ~/.cargo/bin/c2rust ~/.cargo/bin/c2rust-${{ matrix.asset_postfix }}

    - name: Revision
      id: revision
      run: |
        revision=$(curl -s https://api.github.com/repos/immunant/c2rust/commits/master | jq -r .sha)
        isotime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "revision=$revision" >> $GITHUB_OUTPUT
        echo "tag=nightly-$isotime" >> $GITHUB_OUTPUT
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: c2rust-${{ matrix.asset_postfix }}
        path: ~/.cargo/bin/c2rust-${{ matrix.asset_postfix }}
        if-no-files-found: error
  
  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Merge Artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: c2rust
        pattern: c2rust-*
  
  release:
    needs: [build, merge]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Commit changes
      run: |
        sed -i 's/^Last build:.*$/Last build: ${{ needs.build.outputs.revision }}/' README.md
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Last build: ${{ needs.build.outputs.revision }}"
        git tag -a ${{ needs.build.outputs.tag }} -m "Last build: ${{ needs.build.outputs.revision }}"
        git push

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: c2rust
        path: ~/.cargo/bin
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ~/.cargo/bin/c2rust-*
        tag_name: ${{ needs.build.outputs.tag }}
        body: ${{ needs.build.outputs.revision }}

