name: Build and Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          artifact_name: c2rust
          asset_postfix: linux-amd64
        - os: windows-latest
          artifact_name: c2rust.exe
          asset_postfix: windows-amd64.exe
        - os: macos-latest
          artifact_name: c2rust
          asset_postfix: darwin-amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      run: rustup default stable

    - name: Setup rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: ""

    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential llvm clang libclang-14-dev cmake libssl-dev pkg-config python3 git
        echo "LLVM_CONFIG_PATH=/usr/bin/llvm-config-14" >> $GITHUB_ENV
    
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install llvm python3 cmake openssl
        echo "LLVM_CONFIG_PATH=/opt/homebrew/opt/llvm/bin/llvm-config" >> $GITHUB_ENV

    - name: Build
      run: |
        cargo install --git https://github.com/immunant/c2rust.git c2rust --locked --root ~/.cargo/

    - name: Revision
      id: revision
      run: |
        revision=$(curl -s https://api.github.com/repos/immunant/c2rust/commits/master | jq -r .sha)
        echo "revision=$revision" >> $GITHUB_OUTPUT
    
    - name: Commit changes
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sed -i 's/^Last build:.*$/Last build: ${{ steps.revision.outputs.revision }}/' README.md
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Last build: ${{ steps.revision.outputs.revision }}"
        git tag -a ${{ steps.revision.outputs.revision }} -m "Last build: ${{ steps.revision.outputs.revision }}"
        git push
    
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: Nightly build ${{ steps.revision.outputs.revision }}
        asset_name: c2rust-${{ matrix.asset_postfix }}
        file: ~/.cargo/bin/c2rust
